language: node_js

node_js:
  - 12

cache:
  npm: true
  directories:
    - ./node_modules

before_script:
  - npm install

script:
  - npm run build

before_deploy:
  - zip -jr couchman-${TRAVIS_TAG}.zip dist
  - tar -zcf couchman-${TRAVIS_TAG}.tar.gz dist

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    files:
      - "couchman-${TRAVIS_TAG}.zip"
      - "couchman-${TRAVIS_TAG}.tar.gz"
    skip_cleanup: true
    on:
      tags: true